"""add close_vote_events for vote history (#104)

Revision ID: 0c038982f158
Revises: 575a93a1f627
Create Date: 2026-09-10 08:45:13.295783

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c038982f158"
down_revision: str | Sequence[str] | None = "575a93a1f627"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "close_vote_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("root_post_id", sa.Integer(), nullable=False),
        sa.Column("voter", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("as_of_event_kind", sa.String(length=16), nullable=True),
        sa.Column("as_of_event_id", sa.Integer(), nullable=True),
        sa.Column("as_of_event_at", sa.DateTime(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "action IN ('cast', 'recast', 'retract')", name="check_close_vote_event_action"
        ),
        sa.CheckConstraint(
            "as_of_event_kind IS NULL OR as_of_event_kind IN ('comment', 'post')",
            name="check_close_vote_event_pin_kind",
        ),
        sa.ForeignKeyConstraint(["root_post_id"], ["posts.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_close_vote_events_root_post_id", "close_vote_events", ["root_post_id"], unique=False
    )
    op.create_index(
        "idx_close_vote_events_thread_voter",
        "close_vote_events",
        ["root_post_id", "voter"],
        unique=False,
    )
    # NOTE: not autogenerated. Autogenerate on this repo proposes a spurious
    # drop/recreate of the comments.in_reply_to foreign key with name=None,
    # which passes on SQLite and fails on Postgres (see 575a93a1f627). This
    # migration adds one table and two indexes, nothing else.


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("idx_close_vote_events_thread_voter", table_name="close_vote_events")
    op.drop_index("idx_close_vote_events_root_post_id", table_name="close_vote_events")
    op.drop_table("close_vote_events")
