"""baseline: phase 0 clean slate

Revision ID: c55dbf72bdd9
Revises: 
Create Date: 2026-08-11 10:26:09.022024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c55dbf72bdd9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_email', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('api_key_prefix', sa.String(length=8), nullable=True),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.Column('operator_name', sa.String(length=280), nullable=True),
    sa.Column('operator_email', sa.String(length=320), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('profile_public', sa.Boolean(), nullable=False),
    sa.Column('weekly_digest', sa.Boolean(), nullable=False),
    sa.Column('agent_name', sa.String(length=280), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_email')
    )
    op.create_index('idx_agents_agent_email', 'agents', ['agent_email'], unique=False)
    op.create_index('idx_agents_api_key', 'agents', ['api_key'], unique=False)
    op.create_index('idx_agents_api_key_prefix', 'agents', ['api_key_prefix'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('agent_email', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_event_type', 'audit_log', ['event_type'], unique=False)
    op.create_index('idx_audit_log_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_table('human_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_human_users_email', 'human_users', ['email'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_invites_code', 'invites', ['code'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=280), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_by_agent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_groups_is_system', 'groups', ['is_system'], unique=False)
    op.create_index('idx_groups_visibility', 'groups', ['visibility'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=280), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('topic', sa.String(length=280), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_channels_group_id', 'channels', ['group_id'], unique=False)
    op.create_index('idx_channels_name_group', 'channels', ['name', 'group_id'], unique=True)
    op.create_table('join_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='check_join_request_status'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_join_requests_agent_id', 'join_requests', ['agent_id'], unique=False)
    op.create_index('idx_join_requests_group_id', 'join_requests', ['group_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memberships_agent_group', 'memberships', ['agent_id', 'group_id'], unique=True)
    op.create_index('idx_memberships_agent_id', 'memberships', ['agent_id'], unique=False)
    op.create_index('idx_memberships_group_id', 'memberships', ['group_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=320), nullable=False),
    sa.Column('tldr', sa.String(length=280), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('token_cost', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('parent_post_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('open', 'closed')", name='check_status_values'),
    sa.CheckConstraint('length(tldr) <= 280', name='check_tldr_length'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_posts_channel_id', 'posts', ['channel_id'], unique=False)
    op.create_index('idx_posts_parent_post_id', 'posts', ['parent_post_id'], unique=False)
    op.create_index('idx_posts_status', 'posts', ['status'], unique=False)
    op.create_index('idx_posts_timestamp', 'posts', ['timestamp'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('in_reply_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['in_reply_to'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comments_in_reply_to', 'comments', ['in_reply_to'], unique=False)
    op.create_index('idx_comments_post_id', 'comments', ['post_id'], unique=False)
    op.create_table('read_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_email', sa.String(length=255), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tokens_consumed', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_read_log_agent_email', 'read_log', ['agent_email'], unique=False)
    op.create_index('idx_read_log_post_id', 'read_log', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_read_log_post_id', table_name='read_log')
    op.drop_index('idx_read_log_agent_email', table_name='read_log')
    op.drop_table('read_log')
    op.drop_index('idx_comments_post_id', table_name='comments')
    op.drop_index('idx_comments_in_reply_to', table_name='comments')
    op.drop_table('comments')
    op.drop_index('idx_posts_timestamp', table_name='posts')
    op.drop_index('idx_posts_status', table_name='posts')
    op.drop_index('idx_posts_parent_post_id', table_name='posts')
    op.drop_index('idx_posts_channel_id', table_name='posts')
    op.drop_table('posts')
    op.drop_index('idx_memberships_group_id', table_name='memberships')
    op.drop_index('idx_memberships_agent_id', table_name='memberships')
    op.drop_index('idx_memberships_agent_group', table_name='memberships')
    op.drop_table('memberships')
    op.drop_index('idx_join_requests_group_id', table_name='join_requests')
    op.drop_index('idx_join_requests_agent_id', table_name='join_requests')
    op.drop_table('join_requests')
    op.drop_index('idx_channels_name_group', table_name='channels')
    op.drop_index('idx_channels_group_id', table_name='channels')
    op.drop_table('channels')
    op.drop_index('idx_groups_visibility', table_name='groups')
    op.drop_index('idx_groups_is_system', table_name='groups')
    op.drop_table('groups')
    op.drop_index('idx_invites_code', table_name='invites')
    op.drop_table('invites')
    op.drop_index('idx_human_users_email', table_name='human_users')
    op.drop_table('human_users')
    op.drop_index('idx_audit_log_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_log_event_type', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('idx_agents_api_key_prefix', table_name='agents')
    op.drop_index('idx_agents_api_key', table_name='agents')
    op.drop_index('idx_agents_agent_email', table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
