"""Auto-generate STATUS.md from live GitHub issue state.

Queries GitHub Issues via `gh` CLI and rewrites STATUS.md so the phase/issue
tracking never goes stale. Safe to run repeatedly — idempotent output.

Usage:
    python scripts/update_status.py
    python scripts/update_status.py --repo owner/repo
    python scripts/update_status.py --dry-run   # print to stdout, no file write
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

REPO = "mostlycopypaste/stoa"
REPO_URL = f"https://github.com/{REPO}"
STATUS_PATH = Path(__file__).parent.parent / "STATUS.md"

# Labels that map to a phase section
PHASE_LABELS: dict[str, str] = {
    "phase:1-mvp": "Phase 1 — MVP",
    "phase:6-deployment": "Phase 6 — Deployment",
}


def fetch_issues(repo: str) -> list[dict]:  # type: ignore[type-arg]
    """Run `gh issue list` and return parsed JSON."""
    cmd = [
        "gh",
        "issue",
        "list",
        "--repo",
        repo,
        "--state",
        "all",
        "--json",
        "number,title,state,labels,assignees",
        "--limit",
        "200",
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, check=True)
    return json.loads(result.stdout)  # type: ignore[no-any-return]


def label_names(issue: dict) -> list[str]:  # type: ignore[type-arg]
    """Extract label name strings from an issue dict."""
    return [lbl["name"] for lbl in issue.get("labels", [])]


def issue_state_icon(state: str) -> str:
    return "✅" if state == "CLOSED" else "🔲"


def assignee_list(issue: dict) -> str:  # type: ignore[type-arg]
    assignees = issue.get("assignees", [])
    if not assignees:
        return ""
    names = [a.get("login", "") for a in assignees]
    return " (" + ", ".join(f"@{n}" for n in names if n) + ")"


def format_issue_row(issue: dict) -> str:  # type: ignore[type-arg]
    icon = issue_state_icon(issue["state"])
    num = issue["number"]
    title = issue["title"]
    url = f"{REPO_URL}/issues/{num}"
    assignees = assignee_list(issue)
    return f"- {icon} [#{num}]({url}) {title}{assignees}"


def group_by_phase(issues: list[dict]) -> dict[str, list[dict]]:  # type: ignore[type-arg]
    """Group issues by their phase: label; issues without a phase go to 'Unphased'."""
    groups: dict[str, list[dict]] = {label: [] for label in PHASE_LABELS}
    groups["Unphased"] = []

    for issue in issues:
        lbls = label_names(issue)
        matched_phase = None
        for lbl in PHASE_LABELS:
            if lbl in lbls:
                matched_phase = lbl
                break
        if matched_phase:
            groups[matched_phase].append(issue)
        else:
            groups["Unphased"].append(issue)

    return groups


def phase_progress(issues: list[dict]) -> tuple[int, int]:  # type: ignore[type-arg]
    """Return (closed, total) for a list of issues."""
    total = len(issues)
    closed = sum(1 for i in issues if i["state"] == "CLOSED")
    return closed, total


def render_status(issues: list[dict], repo: str, generated_at: str) -> str:  # type: ignore[type-arg]
    """Render the full STATUS.md content from the issues list."""
    open_issues = [i for i in issues if i["state"] == "OPEN"]
    closed_issues = [i for i in issues if i["state"] == "CLOSED"]

    groups = group_by_phase(issues)

    lines: list[str] = []

    lines.append("# Stoa — Project Status")
    lines.append("")
    lines.append("> Auto-generated by `scripts/update_status.py` from GitHub Issues.")
    lines.append(f"> Last updated: {generated_at} UTC")
    lines.append(f"> Source: [{repo}]({REPO_URL}/issues)")
    lines.append("")

    # Summary counts
    total = len(issues)
    closed = len(closed_issues)
    open_count = len(open_issues)
    lines.append("## Summary")
    lines.append("")
    lines.append("| Total | Open | Closed |")
    lines.append("|-------|------|--------|")
    lines.append(f"| {total} | {open_count} | {closed} |")
    lines.append("")

    # Open issues — actionable view
    lines.append("## Open Issues")
    lines.append("")
    if open_issues:
        for issue in sorted(open_issues, key=lambda i: i["number"]):
            lines.append(format_issue_row(issue))
    else:
        lines.append("_No open issues — all done!_")
    lines.append("")

    # Phase sections
    lines.append("## Issues by Phase")
    lines.append("")

    for lbl, section_title in PHASE_LABELS.items():
        phase_issues = groups.get(lbl, [])
        if not phase_issues:
            continue
        closed_count, total_count = phase_progress(phase_issues)
        lines.append(f"### {section_title} ({closed_count}/{total_count} closed)")
        lines.append("")
        for issue in sorted(phase_issues, key=lambda i: i["number"]):
            lines.append(format_issue_row(issue))
        lines.append("")

    # Unphased section — only render if non-empty
    unphased = groups.get("Unphased", [])
    if unphased:
        closed_count, total_count = phase_progress(unphased)
        lines.append(f"### Unphased ({closed_count}/{total_count} closed)")
        lines.append("")
        for issue in sorted(unphased, key=lambda i: i["number"]):
            lines.append(format_issue_row(issue))
        lines.append("")

    # Closed issues — full list for history
    lines.append("## Closed Issues")
    lines.append("")
    if closed_issues:
        for issue in sorted(closed_issues, key=lambda i: i["number"]):
            lines.append(format_issue_row(issue))
    else:
        lines.append("_No closed issues yet._")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate STATUS.md from live GitHub issue state."
    )
    parser.add_argument(
        "--repo",
        default=REPO,
        help=f"GitHub repo slug (default: {REPO})",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=STATUS_PATH,
        help="Path to write STATUS.md (default: repo root STATUS.md)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print rendered STATUS.md to stdout instead of writing the file",
    )
    args = parser.parse_args()

    try:
        issues = fetch_issues(args.repo)
    except subprocess.CalledProcessError as exc:
        print(f"error: gh issue list failed: {exc.stderr}", file=sys.stderr)
        return 1
    except json.JSONDecodeError as exc:
        print(f"error: could not parse gh output: {exc}", file=sys.stderr)
        return 1

    generated_at = datetime.now(UTC).strftime("%Y-%m-%d %H:%M")
    content = render_status(issues, args.repo, generated_at)

    if args.dry_run:
        print(content)
        return 0

    args.output.write_text(content, encoding="utf-8")
    print(f"wrote {args.output} ({len(issues)} issues)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
